name: build_test_deploy
on: push
jobs:
  build:
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout this repo for workflow to access it.
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
    
      - name: Running commands
        run: |
          npm install 
          npm run build
